targets:
  $default:
    builders:
      freezed|freezed:
        enabled: true

builders:
  freezed:
    import: "package:freezed/builder.dart"
    builder_factories: ["freezed"]
    build_extensions: { ".dart": [".freezed.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - json_serializable|json_serializable
      - source_gen|combining_builder

name: list_interface
description: "Ready to check interfacez"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  http: ^1.2.1
  line_icons: ^2.0.3
  provider: ^6.1.2
  web_socket_channel: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/crypto_icons/

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins.Bold.ttf
        weight: 700
      - asset: fonts/Poppins.SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins.Medium.ttf
        weight: 500
      - asset: fonts/Poppins.Regular.ttf
        weight: 400s